general {
    hide_cursor = true
}

auth {
    grace = 0
}

animations {
    enabled = true
}

input-field {
    size = 250, 50
    position = 0, -80
    halign = center
    valign = center

    outline_thickness = 2
    rounding = 0

    outer_color = rgb(255, 116, 116)
    inner_color = rgba(73, 73, 73, 0.15)
    font_color = rgba(255, 255, 255, 1)
    fail_color = rgba(229, 0, 0, 1)
    check_color = rgba(255, 226, 38, 1)

    fade_on_empty = false
    placeholder_text = <i>Enter Password...</i>
}

label {
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 60
    position = 0, 80
    halign = center
    valign = center
}

background {
    path = ~/.config/wallpapers/soldier-red-bg.jpg
    blur_size = 7
    blur_passes = 1
}